# Generated by Django 3.1.7 on 2021-03-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('produit', '0002_auto_20210313_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATTENTE', 'EN ATTENTE'), ('NONLIVREE', 'EN COURS DE LIVRAISON'), ('LIVRE', 'LIVRÉ')], default=1, max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('produits', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produit.produit')),
            ],
        ),
    ]
